{"question": "\nI am attempting to run the following on a remote backend through QISkit:\n\ntry:\n    import math\n    from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister\n    from qiskit import execute, IBMQ, Aer\n    from qiskit.backends.ibmq import least_busy\n\n    q = QuantumRegister(1, 'q')\n    c1 = ClassicalRegister(1, 'c1')\n    c2 = ClassicalRegister(1, 'c2')\n    qc1 = QuantumCircuit(q, c1)\n    qc2 = QuantumCircuit(q, c2)\n    qc1.ry(math.pi*0.25, q[0])\n    qc2.ry(math.pi*0.25, q[0])\n\n    qc1.measure(q, c1)\n    qc2.measure(q, c2)\n\n    backend_sim = Aer.get_backend('qasm_simulator')\n\n    job_sim1 = execute(qc1, backend_sim)\n    result_sim1 = job_sim1.result()\n\n    job_sim2 = execute(qc2, backend_sim)\n    result_sim2 = job_sim2.result()\n\n    print(\"simulation one: \", result_sim1)\n    print(result_sim1.get_counts(qc1))\n    print(\"simulation two: \", result_sim2)\n    print(result_sim2.get_counts(qc2))\n\n    ibmq_backends = IBMQ.backends()\n\n    print(\"Remote backends: \", ibmq_backends)\n    try:\n        least_busy_device = least_busy(IBMQ.backends(simulator=False))\n        print(\"Running on current least busy device: \", least_busy_device)\n\n        job_exp = execute(qc, least_busy_device, shots=1024, max_credits=10)\n        result_exp = job_exp.result()\n\n        print(\"experiment: \", result_exp)\n        print(result_exp.get_counts(qc))\n    except:\n        print(\"all devices are unavailable.\")\nexcept QiskitError as ex:\n    print('an error occurred. Error = {}'.format(ex))\n\n\nAfter the local qasm simulator runs, I receive:\n\nRemote backends: []\nAll devices are currently unavailable\n\n\nHowever, if I run the \"hello_quantum.py\" example given through IBMQ, I am able to access multiple backends and use the ibm_16_melbourne computer. Interestingly, there seems to be an error in this program specifically.\nAny ideas on what could be going wrong here?\n", "answers": ["\nTo use the remote backends, you need to sign into the IBM Q Experience. This is done with\nIBMQ.load_accounts()\n\n(after IBMQ has been imported, of course). Since IBMQ.backends() returns the list of backends that your account allows you to use, it will return an empty list when you are not signed in.\nAn additional note: If you update to the most recent Qiskit version (as of 2019-02-20) you'll need to use from qiskit.providers.ibmq import least_busy to import least_busy.\n"], "comments": ["I realize I had forgotten to load my account, thank you very much! I am able to now print a list of remote backends and select the least busy device. However, I am still unable to run the simulation through this device for some reason. I receive the same error: \"All devices are currently unavailable\". I have even tried to enable my account again through \"qiskit.IBMQ.enable_account()\" but I receive a warning that my credentials are already in use. Any more suggestions?", "There's a full list of things you can try here quantumcomputing.stackexchange.com/questions/5532/\u2026 Other than that, I'm not sure. Is your account able to run jobs on the Q Experience web interface?", "I was able to get it running now, thank you very much!"], "link": "https://quantumcomputing.stackexchange.com//questions/5511/consistent-qiskit-error-all-devices-are-currently-unavailable?r=SearchResults"}