{"0": {"author": "Jinkai_Tian", "date": "1666850745479", "content": "When building a wheel from the package sources using the direct SDK path, I meet a error on the second step:\n$ cmake --build ./Build --verbose\n/usr/local/bin/cmake -S/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main -B/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build --check-build-system CMakeFiles/Makefile.cmake 0\n/usr/local/bin/cmake -E cmake_progress_start /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/CMakeFiles /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build//CMakeFiles/progress.marks\n/usr/bin/make  -f CMakeFiles/Makefile2 all\nmake[1]: Entering directory '/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build'\n/usr/bin/make  -f _deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/build.make _deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/depend\nmake[2]: Entering directory '/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build'\ncd /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build && /usr/local/bin/cmake -E cmake_depends \"Unix Makefiles\" /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-src/core/src /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-build/core/src /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/DependInfo.cmake --color=\nmake[2]: Leaving directory '/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build'\n/usr/bin/make  -f _deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/build.make _deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/build\nmake[2]: Entering directory '/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build'\n[  1%] Building CXX object _deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o\ncd /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-build/core/src && /usr/local/bin/cmake -E __run_co_compile --tidy=\"clang-tidy;-extra-arg=-std=c++17;--extra-arg-before=--driver-mode=g++\" --source=/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-src/core/src/impl/Kokkos_CPUDiscovery.cpp -- /usr/bin/c++ -DKOKKOS_DEPENDENCE -I/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-build/core/src -I/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-src/core/src -I/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-build -O2 -g -DNDEBUG -fPIC -std=gnu++2a -MD -MT _deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o -MF CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o.d -o CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o -c /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build/_deps/kokkos-src/core/src/impl/Kokkos_CPUDiscovery.cpp\nError running 'clang-tidy': No such file or directory\nmake[2]: *** [_deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/build.make:76: _deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o] Error 1\nmake[2]: Leaving directory '/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build'\nmake[1]: *** [CMakeFiles/Makefile2:1269: _deps/kokkos-build/core/src/CMakeFiles/kokkoscore.dir/all] Error 2\nmake[1]: Leaving directory '/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/Build'\nmake: *** [Makefile:136: all] Error 2\n\nMy platform is:\nConda environment python3.8\ncuQuantum 22.7.1\ngcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1~20.04)\ncmake version 3.25.0-rc2\nI am wandering if there are any suggestions?", "link": "https://discuss.pennylane.ai//t/cannot-install-lightning-gpu-on-ubuntu/2244/1"}, "1": {"author": "CatalinaAlbornoz", "date": "1666990574875", "content": "Hi @Jinkai_Tian, welcome to the forum!\nCan you please post the output of qml.about()?\nAlso, what GPU will you be using?\nI\u2019m thinking that you may be using an old version of PennyLane and PennyLane-Lightning, or it may be an issue with the architecture you\u2019re using.\nAlso, you could try updating your GCC to 11.x.\nIf you do this does the problem get fixed?2 Replies", "link": "https://discuss.pennylane.ai//t/cannot-install-lightning-gpu-on-ubuntu/2244/2"}, "2": {"author": "mlxd", "date": "1666992687253", "content": "Hi @Jinkai_Tian\nJust to jump in and have a look at your error message. We use a tool named clang-tidy to ensure any and all development adheres to a given standard when building the libraries.\nOn your machine this doesn\u2019t appear to be installed. You can try apt install clang-tidy to see if this helps. Otherwise, you can explicitly disable this step using -DENABLE_CLANG_TIDY=off to see if it helps.\nThough, if you are on an x86_64 machine, you can simply pip install lightning.gpu and not build it from scratch with\npython3 -m venv pypenv\nsource ./pyenv/bin/activate\npython -m pip install pennylane pennylane-lightning[gpu] cuquantum\n\nhope this helps.1 Reply1", "link": "https://discuss.pennylane.ai//t/cannot-install-lightning-gpu-on-ubuntu/2244/3"}, "3": {"author": "Jinkai_Tian", "date": "1667465732594", "content": "The GPU I am using is 2080Ti.\nThe output of qml.about() is as follows:\nName: PennyLane\nVersion: 0.26.0\nSummary: PennyLane is a Python quantum machine learning library by Xanadu Inc.\nHome-page: https://github.com/XanaduAI/pennylane\nAuthor:\nAuthor-email:\nLicense: Apache License 2.0\nLocation: /home/joselyn/.conda/envs/quantum38/lib/python3.8/site-packages\nRequires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, retworkx, scipy, semantic-version, toml\nRequired-by: PennyLane-Lightning\nPlatform info:           Linux-5.11.0-34-generic-x86_64-with-glibc2.17\nPython version:          3.8.13\nNumpy version:           1.23.4\nScipy version:           1.9.3\nInstalled devices:\n\nlightning.qubit (PennyLane-Lightning-0.26.1)\ndefault.gaussian (PennyLane-0.26.0)\ndefault.mixed (PennyLane-0.26.0)\ndefault.qubit (PennyLane-0.26.0)\ndefault.qubit.autograd (PennyLane-0.26.0)\ndefault.qubit.jax (PennyLane-0.26.0)\ndefault.qubit.tf (PennyLane-0.26.0)\ndefault.qubit.torch (PennyLane-0.26.0)\ndefault.qutrit (PennyLane-0.26.0)\n\nAnd are there any dependence on CUDA version?", "link": "https://discuss.pennylane.ai//t/cannot-install-lightning-gpu-on-ubuntu/2244/4"}, "4": {"author": "Jinkai_Tian", "date": "1667466428621", "content": "Successfully installed! but get errors when I testing it. Any suggestions?\n$ make test-python\npython3 -I -m pytest tests --tb=short\n====================================== test session starts ========================================================\nplatform linux \u2013 Python 3.9.13, pytest-7.2.0, pluggy-1.0.0\nrootdir: /home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/tests, configfile: pytest.ini\ncollected 645 items / 1 skipped\ntests/test_adjoint_jacobian.py \u2026EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEsss\u2026FFFFFFFFFFFF\u2026                                         [ 31%]\ntests/test_apply.py \u2026EEs                  [ 68%]\ntests/test_comparison.py \u2026Fatal Python error: Segmentation fault\nCurrent thread 0x00007f778e32b280 (most recent call first):\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane_lightning/lightning_qubit.py\u201d, line 200 in apply_lightning\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane_lightning/lightning_qubit.py\u201d, line 169 in apply\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane/_qubit_device.py\u201d, line 315 in execute\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane/_qubit_device.py\u201d, line 586 in batch_execute\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/contextlib.py\u201d, line 79 in inner\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane/interfaces/execution.py\u201d, line 122 in fn\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane/interfaces/execution.py\u201d, line 197 in wrapper\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane/interfaces/autograd.py\u201d, line 110 in _execute\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/autograd/tracer.py\u201d, line 48 in f_wrapped\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane/interfaces/autograd.py\u201d, line 66 in execute\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane/interfaces/execution.py\u201d, line 443 in execute\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pennylane/qnode.py\u201d, line 661 in call\nFile \u201c/home/joselyn/Documents/tianjk/pennylane-lightning-gpu-main/tests/test_comparison.py\u201d, line 249 in test_n_qubit_circuit\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/python.py\u201d, line 195 in pytest_pyfunc_call\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_callers.py\u201d, line 39 in _multicall\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_manager.py\u201d, line 80 in _hookexec\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_hooks.py\u201d, line 265 in call\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/python.py\u201d, line 1789 in runtest\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/runner.py\u201d, line 167 in pytest_runtest_call\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_callers.py\u201d, line 39 in _multicall\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_manager.py\u201d, line 80 in _hookexec\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_hooks.py\u201d, line 265 in call\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/runner.py\u201d, line 260 in \nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/runner.py\u201d, line 339 in from_call\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/runner.py\u201d, line 259 in call_runtest_hook\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/runner.py\u201d, line 220 in call_and_report\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/runner.py\u201d, line 131 in runtestprotocol\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/runner.py\u201d, line 112 in pytest_runtest_protocol\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_callers.py\u201d, line 39 in _multicall\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_manager.py\u201d, line 80 in _hookexec\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_hooks.py\u201d, line 265 in call\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/main.py\u201d, line 349 in pytest_runtestloop\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_callers.py\u201d, line 39 in _multicall\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_manager.py\u201d, line 80 in _hookexec\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_hooks.py\u201d, line 265 in call\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/main.py\u201d, line 324 in _main\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/main.py\u201d, line 270 in wrap_session\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/main.py\u201d, line 317 in pytest_cmdline_main\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_callers.py\u201d, line 39 in _multicall\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_manager.py\u201d, line 80 in _hookexec\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pluggy/_hooks.py\u201d, line 265 in call\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/config/init.py\u201d, line 167 in main\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/_pytest/config/init.py\u201d, line 190 in console_main\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/site-packages/pytest/main.py\u201d, line 5 in \nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/runpy.py\u201d, line 87 in _run_code\nFile \u201c/home/joselyn/.conda/envs/qml-gpu-39/lib/python3.9/runpy.py\u201d, line 197 in _run_module_as_main\nmake: *** [Makefile:70: test-builtin] Segmentation fault (core dumped)", "link": "https://discuss.pennylane.ai//t/cannot-install-lightning-gpu-on-ubuntu/2244/5"}, "5": {"author": "CatalinaAlbornoz", "date": "1667594633771", "content": "Hi @Jinkai_Tian,\nUnfortunately segmentation faults can happen for many different reasons, and it can be hard to debug the cause.\nTalking to @mlxd he suggested doing the following:\nUse your system Python, rather than conda, and create a fresh environment with\npython3 -m venv pypenv \nsource ./pyenv/bin/activate \npython -m pip install pennylane pennylane-lightning[gpu] cuquantum\n\nIf that fails, we may need to see your LD_LIBRARY_PATH with\necho $LD_LIBRARY_PATH\nas something may be causing problems there.\nPlease let us know if this resolves your issue!", "link": "https://discuss.pennylane.ai//t/cannot-install-lightning-gpu-on-ubuntu/2244/6"}}