{"0": {"author": "J_Sheppard", "date": "1632927388901", "content": "I\u2019m trying to import Pennylane for the first time and I keep getting this error for \u2018import pennylane as qml\u2019:\n\nImportError                               Traceback (most recent call last)\n in \n----> 1 import pennylane as qml\n/usr/local/lib/python3.6/dist-packages/pennylane/init.py in \n30 import pennylane.operation\n31 import pennylane.qnn\n\u2014> 32 import pennylane.templates\n33 from pennylane._device import Device, DeviceError\n34 from pennylane._grad import grad, jacobian, finite_diff\n/usr/local/lib/python3.6/dist-packages/pennylane/templates/init.py in \n18 from .broadcast import *\n19 from .decorator import *\n\u2014> 20 from .layer import *\n21 from .layers import *\n22 from .embeddings import *\n/usr/local/lib/python3.6/dist-packages/pennylane/templates/layer.py in \n17 # pylint: disable-msg=too-many-branches,too-many-arguments,protected-access\n18 from pennylane.templates.decorator import template as temp\n\u2014> 19 from pennylane.math import shape\n20\n21\nImportError: cannot import name \u2018shape\u2019\n\nEDIT: I just found a solution. For some reason the later package versions all have import errors. If anyone else gets this run:\npip uninstall pennylane --yes\npip install pennylane==0.12.0\nBest of luck!", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/1"}, "1": {"author": "CatalinaAlbornoz", "date": "1632945180596", "content": "Hi @J_Sheppard, welcome to the forum!\nThank you very much for adding the solution. We will look into why this is happening.\nDon\u2019t hesitate to post any new questions that you may have!", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/2"}, "2": {"author": "CatalinaAlbornoz", "date": "1632948808960", "content": "Hi @J_Sheppard, the problem is happening because you have Python version 3.6.\nTry downloading a newer Python version and then the latest PennyLane releases should work.\nPlease let me know if this helps!2 Replies", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/3"}, "3": {"author": "raghavv", "date": "1639138655426", "content": "Got the same error. So, created a new environment with Python3.8 and it imported fine> Sharing the commands used.\n\u200bconda create -n penny python=3.8\nconda activate penny\n\u200b pip install pennylane --upgrade\nThank you", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/4"}, "4": {"author": "CatalinaAlbornoz", "date": "1639150549065", "content": "Hi @raghavv, I\u2019m glad you were able to solve it!\nI do recommend that you always use a virtual environment with your projects.\nLet us know if you have any further questions and enjoy using PennyLane!", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/5"}, "5": {"author": "raghavv", "date": "1639159870791", "content": "thank you @CatalinaAlbornoz for the kind information. I have been trying to run some quantum chemistry calculation, will let you know . Thank you.", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/6"}, "6": {"author": "EvanPeters", "date": "1643237324065", "content": "Just an FYI, on the installation webpage https://pennylane.ai/install.html?version=stable 15 the banner still says \u201cPennyLane supports Python 3.6 or newer.\u201d \u2013 this might be confusing for some people doing the install", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/7"}, "7": {"author": "josh", "date": "1643263557869", "content": "oops, nice catch @EvanPeters, I\u2019ll correct this.", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/8"}, "8": {"author": "Nina", "date": "1673764654503", "content": "Hello @CatalinaAlbornoz ! I too am facing the same issue what @J_Sheppard has mentioned! I have python version=3.10.8 & pennylane= 0.28.0. I also tried to degrade the version to 0.19.0 but i face new error saying\nFile \u201cC:\\Users\\vaishnavi.chandilkar\\Anaconda3\\envs\\maus\\lib\\site-packages\\pennylane\\math\\single_dispatch.py\u201d, line 293, in \ndel ar.autoray._FUNCS[\u201ctorch\u201d, \u201clinalg.eigh\u201d]\nKeyError: (\u2018torch\u2019, \u2018linalg.eigh\u2019).\nHow can fix the error?", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/9"}, "9": {"author": "CatalinaAlbornoz", "date": "1674500823719", "content": "Hi @Nina,\nUsually having the latest Python and PennyLane versions is best. Using Python 3.10.8 and PennyLane 0.28 shouldn\u2019t cause any problems. I would recommend that you follow these steps:\nCreate a new conda environment with:\nconda create --name name_of_your_environment python=3.10.8\nActivate the environment:\nconda activate name_of_your_environment\nAfter this you can install the needed packages:\npython -m pip install pennylane\nPlease let me know if this works for you!", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/10"}, "10": {"author": "Nina", "date": "1674514054572", "content": "Ok. I will try to upgrade and see how it works!!", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/11"}, "11": {"author": "Nina", "date": "1674592658302", "content": "I am facing another problem with respect to shape of the features:\nI am passing features of size (9344,) to Amplitude embedding with padding value = 7440. When i perform reshape, it throws an error:\nAttempt to convert a value (AmplitudeEmbedding(<tf.Tensor: shape=(16384,), dtype=complex128, numpy=\narray([0.        +0.j, 0.        +0.j, 0.        +0.j, ...,\n       0.01191828+0.j, 0.01191828+0.j, 0.01191828+0.j])>, wires=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])) with an unsupported type (<class 'pennylane.templates.embeddings.amplitude.AmplitudeEmbedding'>) to a Tensor.\n\nMy code is\ndef circuit(inputs):\n            output1 = qml.AmplitudeEmbedding(features=inputs, wires=range(14), pad_with=7040, normalize=True)\n            output = tf.reshape(output1, (-1, 73,128)) \n            return qml.expval(qml.PauliZ(0))\n\nMy input feature has shape (9334, ), pad_with = 2^14 - 9344 =  7040. using numpy also throw same error. Can you tell me how do i reshape my features into (None, 73,128) for batch_size = 8?", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/12"}, "12": {"author": "CatalinaAlbornoz", "date": "1674753731783", "content": "Hi @Nina,\nNotice that qml.AmplitudeEmbedding embeds your data into the circuit. It\u2019s not something that returns an output that you would want to use. You can learn more about this and other templates in the PennyLane docs!\nIf you want to reshape the measurement output of your circuit, you will need to do it outside of the circuit.\nHere\u2019s a simple example with a reshape:\n# We import our favourite libraries\nimport pennylane as qml\nfrom pennylane import numpy as np\n\n# We create a device\ndev = qml.device('lightning.qubit',wires=4)\n\n# We create a qnode\n@qml.qnode(dev)\ndef circuit(params):\n    # We add some gates\n    # Notice that the params argument can be a tensor\n    qml.RX(params[0,0],wires=0)\n    qml.RX(params[0,1],wires=1)\n    qml.RX(params[1,0],wires=2)\n    qml.RX(params[1,1],wires=3)\n    # We return a single measurement or a list of measurements\n    return [qml.expval(qml.PauliZ(0)),qml.expval(qml.PauliZ(1)),qml.expval(qml.PauliX(2)),qml.expval(qml.PauliX(3))]\n\n# We define a value for our parameters\nparams = np.array([[0,1],[2,3]],requires_grad=True)\n\n# We run the circuit and store the output in a variable\nmeasurement = circuit(params)\n# We can reshape the measurement output\nreshaped_measurement = measurement.reshape(2,2)\n\nprint('Measurement: ',measurement)\nprint('reshaped_measurement: ',reshaped_measurement)\n\nAs you can see the measurement is a list and then outside of the circuit we reshape the output.\nPlease let me know if this helps!", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/13"}, "13": {"author": "Nina", "date": "1674863879982", "content": "But for batched tensor, the above mentioned method is not working. For example:\nN = 14\nn_layers = 3\nwires = range(N)\ndev = qml.device(\"default.qubit\", wires=n_qubits)\n\n@qml.qnode(dev)\ndef circuit(inputs):\n    qml.AmplitudeEmbedding(features=inputs, wires=wires, pad_with=7040, normalize=True)\n    return (qml.expal(qml.PauliZ(wires=i)) for i in range(n_qubits))\n\nq = tf.ones(shape=(2,73,128))\na = Flatten()(q)\nd = circuit(a)\n\nWhen i print d value, it gives following error:\n~\\Anaconda3\\envs\\maus\\lib\\site-packages\\pennylane\\templates\\embeddings\\amplitude.py in _preprocess(features, wires, pad_with, normalize)\n    181 \n    182         if batched and qml.math.get_interface(features) == \"tensorflow\":\n--> 183             raise ValueError(\"AmplitudeEmbedding does not support batched Tensorflow features.\")\n    184 \n    185         features_batch = features if batched else [features]\n\nValueError: AmplitudeEmbedding does not support batched Tensorflow features.\n\nIf i print shape of d,it gives me (2,). Why does it take only batch size? Is there any alternative method where i can use batched features as input?\n", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/14"}, "14": {"author": "CatalinaAlbornoz", "date": "1675132883738", "content": "Hi @Nina,\nThank you for adding these details. As the error message mentions, AmplitudeEmbedding does not support batched Tensorflow features. This means that you should change one of the following:\n\nOption 1: Change the embedding from AmplitudeEmbedding to something else such as AngleEmbedding\n\nOption 2: Change from using TensorFlow to using PyTorch. Do you absolutely need to use TensorFlow?\nOption 3: Keep using AmplitudeEmbedding and TensorFlow but stop using batches.\n\nHere\u2019s a code example for option 1:\nimport pennylane as qml\nimport tensorflow as tf\n\nn_qubits = 2\ndev = qml.device(\"default.qubit\", wires=n_qubits)\n\n@qml.qnode(dev, interface=\"tf\")\ndef circuit(inputs):\n    qml.AngleEmbedding(features=inputs, wires=range(n_qubits))\n    return [qml.expval(qml.PauliZ(wires=i)) for i in range(n_qubits)]\n\nq = tf.ones(shape=(2,73,128))\na = tf.reshape(q,[73*128,2])\nd = circuit(a)\n\nNote that the last dimension in \u2018a\u2019 needs to be smaller or equal to the number of qubits. In this case 2 qubits.\nAlso note that I changed some other details such as a typo you had in \u2018expval\u2019 and changing the return statement to be a list instead of a tuple.\nPlease let me know if this helps!2 Replies", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/15"}, "15": {"author": "Nina", "date": "1675195945136", "content": "Thank you @CatalinaAlbornoz . I will try to opt these options and see how it works!", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/16"}, "16": {"author": "jracle", "date": "1699450509651", "content": "Hello, I have also encountered this issue in recent experiments. I am disappointed and confused that AmplitudeEmbedding cannot be used with batch in TensorFlow, as I am more accustomed to the usage of model.fit in Keras. Although I can use a for loop as a workaround for training, I have found that this significantly increases the training time for the model.\nOut of curiosity, I would like to inquire why PennyLane did not choose to support batch mode for AmplitudeEmbedding in TensorFlow. Is this a feature that is planned for future updates?\n(I noticed that AmplitudeEmbedding seems to be able to achieve batch computations in general cases by adding @qml.batch_params, so is there any additional code implementation issue involved?)", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/17"}, "17": {"author": "isaacdevlugt", "date": "1699543504760", "content": "Hey @jracle! Welcome to the forum \nThanks for your feedback! We have a feature request open and on our radar for this exact issue: Allow parameter broadcasting in `AmplitudeEmbedding` with TensorFlow \u00b7 Issue #2976 \u00b7 PennyLaneAI/pennylane \u00b7 GitHub 8\nI\u2019ll make sure to put a comment there that we got another request for it. I\u2019ll make sure to update this thread when anything major happens ", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/18"}, "18": {"author": "jracle", "date": "1699583744313", "content": "Thank you @isaacdevlugt .I will also subscribe to this issue. Thank you once again for team\u2019s hard work\uff01", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/19"}, "19": {"author": "Wierichs", "date": "1699604441220", "content": "I opened a pull request implementing batching with Tensorflow (including JIT compilation in Tensorflow): #48181 Reply", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/20"}, "20": {"author": "isaacdevlugt", "date": "1699636132919", "content": "It\u2019s merged! Nice. @jracle if you want to use this feature right away, you\u2019ll need to install PennyLane from source: (1) clone the repository, (2) pip install:\n# download and install the latest source code from GitHub\ngit clone https://github.com/PennyLaneAI/pennylane.git\ncd pennylane\npip install -e .\n\nI recommend doing so in a dedicated virtual environment. Let me know if you have any other questions!", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/21"}, "21": {"author": "jracle", "date": "1699861109590", "content": "The circuit is now running smoothly and working very well.  I would like to express my gratitude once again to the team for their prompt updates!\n\nA small tip: In VSCode, modules installed in editable mode may not be recognized, but they can still function properly. To enable Pylance to recognize the downloaded PennyLane path, you can add it to \"python.analysis.extraPaths\" in the settings.\n", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/22"}, "22": {"author": "CatalinaAlbornoz", "date": "1699976431742", "content": "That\u2019s great @jracle! And thank you @Wierichs for the fix!\nWe have a very small survey for PennyLane v0.33 2, and it would be awesome if you\u2019d give us some feedback and tell us about your needs. Thank you! ", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/23"}, "23": {"author": "jracle", "date": "1700036263217", "content": "It\u2019s done! @CatalinaAlbornoz2", "link": "https://discuss.pennylane.ai//t/importerror-cannot-import-name-shape/1383/24"}}